# Generated by Django 5.0.1 on 2024-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Entrepreneur Name')),
                ('email', models.EmailField(max_length=277, verbose_name='Email')),
            ],
        ),
    ]
